# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0021_auto_20160403_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='/home/nsishell/navalsystemsinc/nsi_repo/shared/static/forms'),
        ),
        migrations.AlterField(
            model_name='imageitem',
            name='image',
            field=models.ImageField(upload_to='/home/nsishell/navalsystemsinc/nsi_repo/shared/static/img/slides'),
        ),
        migrations.AlterField(
            model_name='taskorder',
            name='document',
            field=models.FileField(upload_to='/home/nsishell/navalsystemsinc/nsi_repo/shared/static/documents'),
        ),
    ]
